<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKGCoFMv\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKGCoFMv/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerKGCoFMv.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerKGCoFMv\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerKGCoFMv\appAppKernelProdContainer([
    'container.build_hash' => 'KGCoFMv',
    'container.build_id' => '83dd84d0',
    'container.build_time' => 1731876099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKGCoFMv');
