<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.files_manager' shared service.

return $this->services['mbo.modules.files_manager'] = new \PrestaShop\Module\Mbo\Module\FilesManager(($this->services['mbo.addons.data_provider'] ?? $this->load('getMbo_Addons_DataProviderService.php')), ($this->services['prestashop.module.factory.sourcehandler'] ?? $this->load('getPrestashop_Module_Factory_SourcehandlerService.php')));
